const invoke = (channel: string, ...args: any[]) => {
  if (window.electron?.ipc?.invoke) {
    return window.electron.ipc.invoke(channel, ...args);
  }
  console.warn(`IPC not available for channel: ${channel}`);
  return Promise.resolve(null);
};

export const api = {
  steam: {
    getLibrary: () => invoke('steam:get-library'),
    getAchievements: (appId: number) => invoke('steam:get-achievements', appId),
    getPlaytime: (appId: number) => invoke('steam:get-playtime', appId),
    launchGame: (appId: number, args?: string[]) => invoke('steam:launch-game', appId, args),
    getDepots: (appId: number) => invoke('steam:get-depots', appId),
    downloadDepot: (appId: number, depotId: number, manifestId: number) => invoke('steam:download-depot', appId, depotId, manifestId),
    getWorkshopItems: (appId: number) => invoke('steam:get-workshop-items', appId),
    subscribeWorkshop: (publishedFileId: string) => invoke('steam:subscribe-workshop', publishedFileId),
    unsubscribeWorkshop: (publishedFileId: string) => invoke('steam:unsubscribe-workshop', publishedFileId),
    getDlc: (appId: number) => invoke('steam:get-dlc', appId),
    installDlcUnlocker: (appId: number, type: string) => invoke('steam:install-dlc-unlocker', appId, type),
    getControllerConfig: (appId: number) => invoke('steam:get-controller-config', appId),
    setControllerConfig: (appId: number, config: any) => invoke('steam:set-controller-config', appId, config),
  },
  torrent: {
    addMagnet: (magnet: string, options?: any) => invoke('torrent:add-magnet', magnet, options),
    addTorrent: (path: string, options?: any) => invoke('torrent:add-torrent', path, options),
    getTorrents: () => invoke('torrent:get-torrents'),
    pause: (hash: string) => invoke('torrent:pause', hash),
    resume: (hash: string) => invoke('torrent:resume', hash),
    remove: (hash: string, deleteFiles?: boolean) => invoke('torrent:remove', hash, deleteFiles),
    getHydraSources: () => invoke('torrent:get-hydra-sources'),
    searchHydra: (query: string) => invoke('torrent:search-hydra', query),
  },
  emulator: {
    getEmulators: () => invoke('emulator:get-emulators'),
    detectEmulators: () => invoke('emulator:detect-emulators'),
    launchRom: (emulatorId: string, romPath: string, args?: string[]) => invoke('emulator:launch-rom', emulatorId, romPath, args),
    getRoms: (system?: string) => invoke('emulator:get-roms', system),
    scanRoms: (paths: string[]) => invoke('emulator:scan-roms', paths),
    getRetroArchCores: () => invoke('emulator:get-retroarch-cores'),
    installCore: (coreName: string) => invoke('emulator:install-core', coreName),
    updateCores: () => invoke('emulator:update-cores'),
  },
  roms: {
    getMetadata: (romPath: string) => invoke('roms:get-metadata', romPath),
    scrapeMetadata: (romPaths: string[], source: string) => invoke('roms:scrape-metadata', romPaths, source),
    getSources: () => invoke('roms:get-sources'),
    search: (query: string, system?: string) => invoke('roms:search', query, system),
    download: (url: string, destination: string) => invoke('roms:download', url, destination),
  },
  mods: {
    getMods: (gameId: string) => invoke('mods:get-mods', gameId),
    installMod: (gameId: string, modId: string, source: string) => invoke('mods:install', gameId, modId, source),
    uninstallMod: (gameId: string, modId: string) => invoke('mods:uninstall', gameId, modId),
    enableMod: (gameId: string, modId: string) => invoke('mods:enable', gameId, modId),
    disableMod: (gameId: string, modId: string) => invoke('mods:disable', gameId, modId),
    getLoadOrder: (gameId: string) => invoke('mods:get-load-order', gameId),
    setLoadOrder: (gameId: string, order: string[]) => invoke('mods:set-load-order', gameId, order),
    getSources: () => invoke('mods:get-sources'),
    search: (gameId: string, query: string) => invoke('mods:search', gameId, query),
    installModlist: (gameId: string, modlistUrl: string) => invoke('mods:install-modlist', gameId, modlistUrl),
  },
  multiplayer: {
    getClients: () => invoke('multiplayer:get-clients'),
    launchClient: (clientId: string, gameId?: string) => invoke('multiplayer:launch-client', clientId, gameId),
    getServers: (clientId: string) => invoke('multiplayer:get-servers', clientId),
    connectServer: (clientId: string, serverId: string) => invoke('multiplayer:connect-server', clientId, serverId),
    installClient: (clientId: string) => invoke('multiplayer:install-client', clientId),
  },
  cloudGaming: {
    getServices: () => invoke('cloud-gaming:get-services'),
    launchService: (serviceId: string, gameId?: string) => invoke('cloud-gaming:launch-service', serviceId, gameId),
    getGames: (serviceId: string) => invoke('cloud-gaming:get-games', serviceId),
    connectHost: (host: string, port: number) => invoke('cloud-gaming:connect-host', host, port),
  },
  optimization: {
    getProfiles: () => invoke('optimization:get-profiles'),
    createProfile: (profile: any) => invoke('optimization:create-profile', profile),
    updateProfile: (id: string, profile: any) => invoke('optimization:update-profile', id, profile),
    deleteProfile: (id: string) => invoke('optimization:delete-profile', id),
    applyProfile: (gameId: string, profileId: string) => invoke('optimization:apply-profile', gameId, profileId),
    getTools: () => invoke('optimization:get-tools'),
    installTool: (toolId: string) => invoke('optimization:install-tool', toolId),
    autoOptimize: (gameId: string) => invoke('optimization:auto-optimize', gameId),
  },
  achievements: {
    get: (gameId: string, platform: string) => invoke('achievements:get', gameId, platform),
    unlock: (gameId: string, achievementId: string, platform: string) => invoke('achievements:unlock', gameId, achievementId, platform),
    getRarity: (gameId: string, achievementId: string, platform: string) => invoke('achievements:get-rarity', gameId, achievementId, platform),
    getLeaderboard: (gameId: string, platform: string) => invoke('achievements:get-leaderboard', gameId, platform),
    notify: (achievement: any) => invoke('achievements:notify', achievement),
  },
  saves: {
    get: (gameId: string) => invoke('saves:get', gameId),
    backup: (gameId: string, saveId: string) => invoke('saves:backup', gameId, saveId),
    restore: (gameId: string, backupId: string) => invoke('saves:restore', gameId, backupId),
    convert: (saveId: string, targetPlatform: string) => invoke('saves:convert', saveId, targetPlatform),
    getLocations: (gameId: string) => invoke('saves:get-locations', gameId),
    setAutoBackup: (enabled: boolean) => invoke('saves:auto-backup', enabled),
  },
  library: {
    getGames: () => invoke('library:get-games'),
    addGame: (game: any) => invoke('library:add-game', game),
    removeGame: (gameId: string) => invoke('library:remove-game', gameId),
    updateGame: (gameId: string, data: any) => invoke('library:update-game', gameId, data),
    getViews: () => invoke('library:get-views'),
    createView: (view: any) => invoke('library:create-view', view),
    getStats: () => invoke('library:get-stats'),
    getBacklog: () => invoke('library:get-backlog'),
    addToBacklog: (gameId: string) => invoke('library:add-to-backlog', gameId),
    rateGame: (gameId: string, rating: number) => invoke('library:rate-game', gameId, rating),
    addNote: (gameId: string, note: string) => invoke('library:add-note', gameId, note),
    detectDuplicates: () => invoke('library:detect-duplicates'),
    scanPortable: (path: string) => invoke('library:scan-portable', path),
  },
  social: {
    getFriends: () => invoke('social:get-friends'),
    getActivity: () => invoke('social:get-activity'),
    joinFriend: (friendId: string, gameId: string) => invoke('social:join-friend', friendId, gameId),
    inviteFriend: (friendId: string, gameId: string) => invoke('social:invite-friend', friendId, gameId),
    shareMedia: (media: any) => invoke('social:share-media', media),
    getReviews: (gameId: string) => invoke('social:get-reviews', gameId),
    submitReview: (gameId: string, review: any) => invoke('social:submit-review', gameId, review),
    getLeaderboards: (gameId: string) => invoke('social:get-leaderboards', gameId),
  },
  discord: {
    updatePresence: (presence: any) => invoke('discord:update-presence', presence),
    clearPresence: () => invoke('discord:clear-presence'),
    getConnectedUsers: () => invoke('discord:get-connected-users'),
  },
  metadata: {
    search: (query: string) => invoke('metadata:search', query),
    getDetails: (id: string, source: string) => invoke('metadata:get-details', id, source),
    enrich: (gameId: string) => invoke('metadata:enrich', gameId),
    getSources: () => invoke('metadata:get-sources'),
  },
  downloads: {
    start: (url: string, options?: any) => invoke('downloads:start', url, options),
    pause: (id: string) => invoke('downloads:pause', id),
    resume: (id: string) => invoke('downloads:resume', id),
    cancel: (id: string) => invoke('downloads:cancel', id),
    get: () => invoke('downloads:get'),
    setAria2: (options: any) => invoke('downloads:set-aria2', options),
  },
  settings: {
    get: (key: string) => invoke('settings:get', key),
    set: (key: string, value: any) => invoke('settings:set', key, value),
    getAll: () => invoke('settings:get-all'),
    reset: (key?: string) => invoke('settings:reset', key),
  },
  hoardSync: {
    backupGame: (gameId: string, gameName: string, sourcePath: string) => invoke('hoard-sync:backup', gameId, gameName, sourcePath),
    getSnapshots: (gameId: string) => invoke('hoard-sync:get-snapshots', gameId),
    restoreSnapshot: (snapshotId: string, destinationPath: string) => invoke('hoard-sync:restore', snapshotId, destinationPath),
    getStorageStats: () => invoke('hoard-sync:get-storage-stats'),
  },
  themes: {
    get: () => invoke('themes:get'),
    setTheme: (themeId: string) => invoke('themes:set', themeId),
    install: (themeData: any) => invoke('themes:install', themeData),
    create: (theme: any) => invoke('themes:create', theme),
    getMarketplace: () => invoke('themes:marketplace'),
  },
  plugins: {
    get: () => invoke('plugins:get'),
    enable: (id: string) => invoke('plugins:enable', id),
    disable: (id: string) => invoke('plugins:disable', id),
    install: (url: string) => invoke('plugins:install', url),
    getMarketplace: () => invoke('plugins:marketplace'),
  },
  update: {
    getState: () => invoke('update:get-state'),
    check: () => invoke('update:check'),
    download: () => invoke('update:download'),
    install: () => invoke('update:install'),
    openReleases: () => invoke('update:open-releases'),
  },
  system: {
    openExternal: (url: string) => invoke('system:open-external', url),
    showInFolder: (path: string) => invoke('system:show-in-folder', path),
    openPath: (path: string) => invoke('system:open-path', path),
    getInfo: () => invoke('system:get-info'),
    minimize: () => invoke('system:minimize'),
    maximize: () => invoke('system:maximize'),
    close: () => invoke('system:close'),
    setFullscreen: (fullscreen: boolean) => invoke('system:set-fullscreen', fullscreen),
  },
};
