export const LANGS = ['en', 'es', 'fr', 'de', 'ja', 'zh', 'ru', 'pt', 'it'] as const;
export type Lang = (typeof LANGS)[number];

const dict: Record<Lang, Record<string, string>> = {
  en: { library: 'Library', steam: 'Steam', downloads: 'Downloads', consoles: 'Consoles', store: 'Store', mods: 'Mods', multiplayer: 'Multiplayer', cloud: 'Cloud Gaming', optimization: 'Optimization', achievements: 'Achievements', saves: 'Saves', hoard: 'Hoard Sync', friends: 'Friends', profiles: 'Profiles', plugins: 'Plugins', themes: 'Themes', settings: 'Settings', profileTitle: 'Create your profile', profileBody: 'This name stays on this PC. You can add more later in Profiles.', continue: 'Continue', language: 'Language', open: 'Open', launch: 'Launch', verify: 'Verify', backup: 'Backup', hash: 'SHA256', on: 'On', off: 'Off' },
  es: { library: 'Biblioteca', steam: 'Steam', downloads: 'Descargas', consoles: 'Consolas', store: 'Tienda', mods: 'Mods', multiplayer: 'Multijugador', cloud: 'Juego en la nube', optimization: 'Optimización', achievements: 'Logros', saves: 'Partidas', hoard: 'Hoard Sync', friends: 'Amigos', profiles: 'Perfiles', plugins: 'Plugins', themes: 'Temas', settings: 'Ajustes', profileTitle: 'Crea tu perfil', profileBody: 'Este nombre se queda en este PC. Puedes añadir más en Perfiles.', continue: 'Continuar', language: 'Idioma', open: 'Abrir', launch: 'Iniciar', verify: 'Comprobar', backup: 'Copia', hash: 'SHA256', on: 'Sí', off: 'No' },
  fr: { library: 'Bibliothèque', steam: 'Steam', downloads: 'Téléchargements', consoles: 'Consoles', store: 'Boutique', mods: 'Mods', multiplayer: 'Multijoueur', cloud: 'Cloud gaming', optimization: 'Optimisation', achievements: 'Succès', saves: 'Sauvegardes', hoard: 'Hoard Sync', friends: 'Amis', profiles: 'Profils', plugins: 'Plugins', themes: 'Thèmes', settings: 'Réglages', profileTitle: 'Crée ton profil', profileBody: 'Ce nom reste sur ce PC. Tu pourras en ajouter dans Profils.', continue: 'Continuer', language: 'Langue', open: 'Ouvrir', launch: 'Lancer', verify: 'Vérifier', backup: 'Copie', hash: 'SHA256', on: 'Oui', off: 'Non' },
  de: { library: 'Bibliothek', steam: 'Steam', downloads: 'Downloads', consoles: 'Konsolen', store: 'Store', mods: 'Mods', multiplayer: 'Mehrspieler', cloud: 'Cloud-Gaming', optimization: 'Optimierung', achievements: 'Erfolge', saves: 'Spielstände', hoard: 'Hoard Sync', friends: 'Freunde', profiles: 'Profile', plugins: 'Plugins', themes: 'Themen', settings: 'Einstellungen', profileTitle: 'Profil erstellen', profileBody: 'Dieser Name bleibt auf diesem PC. Weitere legst du unter Profile an.', continue: 'Weiter', language: 'Sprache', open: 'Öffnen', launch: 'Starten', verify: 'Prüfen', backup: 'Sichern', hash: 'SHA256', on: 'An', off: 'Aus' },
  ja: { library: 'ライブラリ', steam: 'Steam', downloads: 'ダウンロード', consoles: 'コンソール', store: 'ストア', mods: 'MOD', multiplayer: 'マルチプレイ', cloud: 'クラウド', optimization: '最適化', achievements: '実績', saves: 'セーブ', hoard: 'Hoard Sync', friends: 'フレンド', profiles: 'プロフィール', plugins: 'プラグイン', themes: 'テーマ', settings: '設定', profileTitle: 'プロフィールを作成', profileBody: 'この名前はこのPCに残ります。あとから追加できます。', continue: '続ける', language: '言語', open: '開く', launch: '起動', verify: '確認', backup: 'バックアップ', hash: 'SHA256', on: 'オン', off: 'オフ' },
  zh: { library: '库', steam: 'Steam', downloads: '下载', consoles: '主机', store: '商店', mods: '模组', multiplayer: '联机', cloud: '云游戏', optimization: '优化', achievements: '成就', saves: '存档', hoard: 'Hoard Sync', friends: '好友', profiles: '配置', plugins: '插件', themes: '主题', settings: '设置', profileTitle: '创建配置', profileBody: '这个名字保存在这台电脑上。之后可以再添加。', continue: '继续', language: '语言', open: '打开', launch: '启动', verify: '校验', backup: '备份', hash: 'SHA256', on: '开', off: '关' },
  ru: { library: 'Библиотека', steam: 'Steam', downloads: 'Загрузки', consoles: 'Консоли', store: 'Магазин', mods: 'Моды', multiplayer: 'Мультиплеер', cloud: 'Облачные игры', optimization: 'Оптимизация', achievements: 'Достижения', saves: 'Сохранения', hoard: 'Hoard Sync', friends: 'Друзья', profiles: 'Профили', plugins: 'Плагины', themes: 'Темы', settings: 'Настройки', profileTitle: 'Создайте профиль', profileBody: 'Имя останется на этом ПК. Другие можно добавить в Профилях.', continue: 'Далее', language: 'Язык', open: 'Открыть', launch: 'Запуск', verify: 'Проверить', backup: 'Копия', hash: 'SHA256', on: 'Вкл', off: 'Выкл' },
  pt: { library: 'Biblioteca', steam: 'Steam', downloads: 'Transferências', consoles: 'Consolas', store: 'Loja', mods: 'Mods', multiplayer: 'Multijogador', cloud: 'Jogos na nuvem', optimization: 'Otimização', achievements: 'Conquistas', saves: 'Gravações', hoard: 'Hoard Sync', friends: 'Amigos', profiles: 'Perfis', plugins: 'Plugins', themes: 'Temas', settings: 'Definições', profileTitle: 'Cria o teu perfil', profileBody: 'Este nome fica neste PC. Podes adicionar mais em Perfis.', continue: 'Continuar', language: 'Idioma', open: 'Abrir', launch: 'Iniciar', verify: 'Verificar', backup: 'Cópia', hash: 'SHA256', on: 'Sim', off: 'Não' },
  it: { library: 'Libreria', steam: 'Steam', downloads: 'Download', consoles: 'Console', store: 'Negozio', mods: 'Mod', multiplayer: 'Multigiocatore', cloud: 'Cloud gaming', optimization: 'Ottimizzazione', achievements: 'Obiettivi', saves: 'Salvataggi', hoard: 'Hoard Sync', friends: 'Amici', profiles: 'Profili', plugins: 'Plugin', themes: 'Temi', settings: 'Impostazioni', profileTitle: 'Crea il profilo', profileBody: 'Questo nome resta su questo PC. Puoi aggiungerne altri in Profili.', continue: 'Continua', language: 'Lingua', open: 'Apri', launch: 'Avvia', verify: 'Verifica', backup: 'Copia', hash: 'SHA256', on: 'Sì', off: 'No' },
};

export function t(lang: string | undefined, key: string) {
  const pack = dict[(lang as Lang) in dict ? (lang as Lang) : 'en'];
  return pack[key] || dict.en[key] || key;
}
